In [1]:
import pandas as pd
import numpy as np

In [63]:
pre_gs = pd.read_csv("./data/purified/gshock.csv")
pre_gs.head(10)

,Unnamed: 0,countryname,year,exchange rate (to $USD),import (thousand $USD),export (thousand $USD),countrycode,GDP(current $USD),general government final consumption expenditure (Current $USD)
0,0,United Arab Emirates,1992,3.671000,65518.024,542953.728,ARE,5.423917e+10,NaN
1,1,Argentina,1992,0.990642,200117.984,124141.240,ARG,2.287886e+11,6.807692e+09
2,2,Australia,1992,1.361648,1671112.960,660796.352,AUS,3.255318e+11,6.346459e+10
3,3,Brazil,1992,0.001953,519302.080,64751.736,BRA,3.281880e+11,5.599876e+10
4,4,Canada,1992,1.208723,1926516.992,653178.048,CAN,5.923877e+11,1.452958e+11
5,5,Switzerland,1992,1.406218,523643.808,159871.008,CHE,2.799214e+11,3.311095e+10
6,6,China,1992,5.514592,NaN,NaN,CHN,4.269157e+11,6.164946e+10
7,7,Germany,1992,1.561650,4014989.056,2447975.424,DEU,2.131572e+12,4.097120e+11
8,8,"Egypt, Arab Rep",1992,3.321748,NaN,NaN,EGY,4.185599e+10,4.363133e+09
9,9,Spain,1992,102.379080,355676.032,353482.240,ESP,6.309160e+11,1.123392e+11

In [6]:
g_list = []

In [109]:
ref_cn = pre_gs[pre_gs['countryname'] == 'China']
ref_cn

,Unnamed: 0,countryname,year,exchange rate (to $USD),import (thousand $USD),export (thousand $USD),countrycode,GDP(current $USD),general government final consumption expenditure (Current $USD)
6,6,China,1992,5.514592,NaN,NaN,CHN,4.269157e+11,6.164946e+10
36,36,China,1993,5.761958,NaN,NaN,CHN,4.447313e+11,6.383113e+10
66,66,China,1994,8.618743,NaN,NaN,CHN,5.643247e+11,7.952032e+10
96,96,China,1995,8.351417,NaN,NaN,CHN,7.345479e+11,9.775446e+10
126,126,China,1996,8.314175,NaN,NaN,CHN,8.637467e+11,1.139993e+11
156,156,China,1997,8.289817,NaN,NaN,CHN,9.616040e+11,1.322459e+11
186,186,China,1998,8.278958,NaN,NaN,CHN,1.029043e+12,1.538009e+11
216,216,China,1999,8.278250,NaN,NaN,CHN,1.093997e+12,1.790402e+11
246,246,China,2000,8.278504,NaN,NaN,CHN,1.211347e+12,2.039718e+11
276,276,China,2001,8.277068,NaN,NaN,CHN,1.339396e+12,2.198409e+11
306,306,China,2002,8.276957,NaN,NaN,CHN,1.470550e+12,2.363236e+11
336,336,China,2003,8.277037,NaN,NaN,CHN,1.660288e+12,2.542600e+11
366,366,China,2004,8.276801,NaN,NaN,CHN,1.955347e+12,2.859762e+11
396,396,China,2005,8.194317,NaN,NaN,CHN,2.285966e+12,3.382695e+11
426,426,China,2006,7.973438,NaN,NaN,CHN,2.752132e+12,4.078801e+11
456,456,China,2007,7.607532,NaN,NaN,CHN,3.550343e+12,5.193002e+11
486,486,China,2008,6.948655,NaN,NaN,CHN,4.594307e+12,6.655136e+11
516,516,China,2009,6.831416,NaN,NaN,CHN,5.101703e+12,7.526530e+11
546,546,China,2010,6.770269,NaN,NaN,CHN,6.087164e+12,8.879358e+11
576,576,China,2011,6.461462,NaN,NaN,CHN,7.551500e+12,1.150763e+12
606,606,China,2012,6.312333,NaN,NaN,CHN,8.532230e+12,1.344345e+12
636,636,China,2013,6.195758,NaN,NaN,CHN,9.570406e+12,1.520165e+12
666,666,China,2014,6.143434,NaN,NaN,CHN,1.047568e+13,1.656943e+12
696,696,China,2015,6.227488,NaN,NaN,CHN,1.106155e+13,1.793950e+12
726,726,China,2016,6.644478,NaN,NaN,CHN,1.123328e+13,1.838186e+12
756,756,China,2017,6.758755,NaN,NaN,CHN,1.231041e+13,2.009657e+12
786,786,China,2018,6.615957,NaN,NaN,CHN,1.389482e+13,2.297620e+12
816,816,China,2019,6.908385,NaN,NaN,CHN,1.427994e+13,2.394818e+12
846,846,China,2020,6.900767,NaN,NaN,CHN,1.468767e+13,2.516018e+12

In [118]:
china_gdp= ref_cn.iloc[0]['GDP(current $USD)']
china_gdp

426915712711.146

In [126]:
pre_gs = pre_gs.dropna()

In [129]:
pre_gs['GShock'] = ''
pre_gs.head(3)

C:\Users\nieh_\AppData\Local\Temp/ipykernel_27960/989753029.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pre_gs['GShock'] = ''

,Unnamed: 0,countryname,year,exchange rate (to $USD),import (thousand $USD),export (thousand $USD),countrycode,GDP(current $USD),general government final consumption expenditure (Current $USD),GShock
1,1,Argentina,1992,0.990642,200117.984,124141.240,ARG,2.287886e+11,6.807692e+09,
2,2,Australia,1992,1.361648,1671112.960,660796.352,AUS,3.255318e+11,6.346459e+10,
3,3,Brazil,1992,0.001953,519302.080,64751.736,BRA,3.281880e+11,5.599876e+10,

In [127]:
for index, row in pre_gs.iterrows():
    if row.

ValueError: Wrong number of items passed 27, placement implies 1

In [7]:
for i in range(1991, 2021):
    temp = pre_gs[pre_gs['year'] == i]
    sigma = 0
    cn_exr = temp[temp['countryname'] == 'China']['exchange rate (to $USD)']
    for index, row in temp.iterrows():
        if row['countryname'] == 'China':
            cn_exr = row['exchange rate (to $USD)']
        if row.isna().any():
            pass
        else:
            sigma = sigma + row['import (thousand $USD)'] * 1000 / row['general government final consumption expenditure (Current $USD)']* (row['import (thousand $USD)'] * 1000 + row['export (thousand $USD)']) / row['GDP(current $USD)'] * 1000 * row['general government final consumption expenditure (Current $USD)']* row['exchange rate (to $USD)']
    res = sigma / cn_exr
    g_list.append(res)
    
g_list

[Series([], Name: exchange rate (to $USD), dtype: float64),
 8603643910023.161,
 9315023475290.916,
 6913813383667.267,
 16105587678526.246,
 15544422233078.666,
 22313164288385.797,
 83978820787928.28,
 74642859980473.6,
 173158450941398.0,
 181121991611447.88,
 196430306173802.72,
 271484720974291.12,
 514128472818433.94,
 562015424279602.2,
 547794437755018.2,
 813504763402435.1,
 1106772080824016.9,
 1128164321331375.0,
 1789738979143911.5,
 3895561519941745.5,
 6221125807368831.0,
 6484444073712788.0,
 7313592764158275.0,
 1.4119029477526816e+16,
 1.887480054890777e+16,
 3.1632485201791932e+16,
 4.770879526098802e+16,
 4.337734323457903e+16,
 6.28156749365571e+16]

In [64]:
data = pre_gs.set_index('year')
data = data.dropna()

In [65]:
data

,Unnamed: 0,countryname,exchange rate (to $USD),import (thousand $USD),export (thousand $USD),countrycode,GDP(current $USD),general government final consumption expenditure (Current $USD)
year,,,,,,,,
1992,1,Argentina,0.990642,2.001180e+05,1.241412e+05,ARG,2.287886e+11,6.807692e+09
1992,2,Australia,1.361648,1.671113e+06,6.607964e+05,AUS,3.255318e+11,6.346459e+10
1992,3,Brazil,0.001953,5.193021e+05,6.475174e+04,BRA,3.281880e+11,5.599876e+10
1992,4,Canada,1.208723,1.926517e+06,6.531780e+05,CAN,5.923877e+11,1.452958e+11
1992,5,Switzerland,1.406218,5.236438e+05,1.598710e+05,CHE,2.799214e+11,3.311095e+10
...,...,...,...,...,...,...,...,...
2020,865,Thailand,31.293673,4.813950e+07,5.051318e+07,THA,4.996818e+11,8.914667e+10
2020,866,Turkey,7.008605,3.731027e+06,2.034642e+07,TUR,7.202894e+11,1.092943e+11
2020,867,United States,1.000000,1.363395e+08,4.524929e+08,USA,2.106047e+13,3.138376e+12
2020,868,Vietnam,23208.369000,7.847307e+07,1.138152e+08,VNM,3.466158e+11,3.285506e+10
2020,869,South Africa,16.459105,2.082454e+07,1.523883e+07,ZAF,3.376197e+11,7.019955e+10

In [66]:
data['deltaGDP'] = data.groupby('countryname')['GDP(current $USD)'].diff()
data

,Unnamed: 0,countryname,exchange rate (to $USD),import (thousand $USD),export (thousand $USD),countrycode,GDP(current $USD),general government final consumption expenditure (Current $USD),deltaGDP
year,,,,,,,,,
1992,1,Argentina,0.990642,2.001180e+05,1.241412e+05,ARG,2.287886e+11,6.807692e+09,NaN
1992,2,Australia,1.361648,1.671113e+06,6.607964e+05,AUS,3.255318e+11,6.346459e+10,NaN
1992,3,Brazil,0.001953,5.193021e+05,6.475174e+04,BRA,3.281880e+11,5.599876e+10,NaN
1992,4,Canada,1.208723,1.926517e+06,6.531780e+05,CAN,5.923877e+11,1.452958e+11,NaN
1992,5,Switzerland,1.406218,5.236438e+05,1.598710e+05,CHE,2.799214e+11,3.311095e+10,NaN
...,...,...,...,...,...,...,...,...,...
2020,865,Thailand,31.293673,4.813950e+07,5.051318e+07,THA,4.996818e+11,8.914667e+10,-3.964802e+10
2020,866,Turkey,7.008605,3.731027e+06,2.034642e+07,TUR,7.202894e+11,1.092943e+11,-6.851671e+10
2020,867,United States,1.000000,1.363395e+08,4.524929e+08,USA,2.106047e+13,3.138376e+12,-1.524487e+11
2020,868,Vietnam,23208.369000,7.847307e+07,1.138152e+08,VNM,3.466158e+11,3.285506e+10,-3.205025e+11
2020,869,South Africa,16.459105,2.082454e+07,1.523883e+07,ZAF,3.376197e+11,7.019955e+10,1.225049e+10

In [67]:
data['deltaGovtExp'] = data.groupby('countryname')['general government final consumption expenditure (Current $USD)'].diff()

data

,Unnamed: 0,countryname,exchange rate (to $USD),import (thousand $USD),export (thousand $USD),countrycode,GDP(current $USD),general government final consumption expenditure (Current $USD),deltaGDP,deltaGovtExp
year,,,,,,,,,,
1992,1,Argentina,0.990642,2.001180e+05,1.241412e+05,ARG,2.287886e+11,6.807692e+09,NaN,NaN
1992,2,Australia,1.361648,1.671113e+06,6.607964e+05,AUS,3.255318e+11,6.346459e+10,NaN,NaN
1992,3,Brazil,0.001953,5.193021e+05,6.475174e+04,BRA,3.281880e+11,5.599876e+10,NaN,NaN
1992,4,Canada,1.208723,1.926517e+06,6.531780e+05,CAN,5.923877e+11,1.452958e+11,NaN,NaN
1992,5,Switzerland,1.406218,5.236438e+05,1.598710e+05,CHE,2.799214e+11,3.311095e+10,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
2020,865,Thailand,31.293673,4.813950e+07,5.051318e+07,THA,4.996818e+11,8.914667e+10,-3.964802e+10,-7.999578e+09
2020,866,Turkey,7.008605,3.731027e+06,2.034642e+07,TUR,7.202894e+11,1.092943e+11,-6.851671e+10,-7.260035e+08
2020,867,United States,1.000000,1.363395e+08,4.524929e+08,USA,2.106047e+13,3.138376e+12,-1.524487e+11,6.590602e+10
2020,868,Vietnam,23208.369000,7.847307e+07,1.138152e+08,VNM,3.466158e+11,3.285506e+10,-3.205025e+11,1.295970e+11
2020,869,South Africa,16.459105,2.082454e+07,1.523883e+07,ZAF,3.376197e+11,7.019955e+10,1.225049e+10,8.267567e+08

In [68]:
data['GShock'] = data['import (thousand $USD)'] / data['general government final consumption expenditure (Current $USD)'] * (data['import (thousand $USD)'] + data['export (thousand $USD)']) / data['GDP(current $USD)'] * 1000 * 1000 * data['general government final consumption expenditure (Current $USD)'].shift(1) 
data

,Unnamed: 0,countryname,exchange rate (to $USD),import (thousand $USD),export (thousand $USD),countrycode,GDP(current $USD),general government final consumption expenditure (Current $USD),deltaGDP,deltaGovtExp,GShock
year,,,,,,,,,,,
1992,1,Argentina,0.990642,2.001180e+05,1.241412e+05,ARG,2.287886e+11,6.807692e+09,NaN,NaN,NaN
1992,2,Australia,1.361648,1.671113e+06,6.607964e+05,AUS,3.255318e+11,6.346459e+10,NaN,NaN,1.284081e+06
1992,3,Brazil,0.001953,5.193021e+05,6.475174e+04,BRA,3.281880e+11,5.599876e+10,NaN,NaN,1.047378e+06
1992,4,Canada,1.208723,1.926517e+06,6.531780e+05,CAN,5.923877e+11,1.452958e+11,NaN,NaN,3.233409e+06
1992,5,Switzerland,1.406218,5.236438e+05,1.598710e+05,CHE,2.799214e+11,3.311095e+10,NaN,NaN,5.610857e+06
...,...,...,...,...,...,...,...,...,...,...,...
2020,865,Thailand,31.293673,4.813950e+07,5.051318e+07,THA,4.996818e+11,8.914667e+10,-3.964802e+10,-7.999578e+09,4.537596e+09
2020,866,Turkey,7.008605,3.731027e+06,2.034642e+07,TUR,7.202894e+11,1.092943e+11,-6.851671e+10,-7.260035e+08,1.017277e+08
2020,867,United States,1.000000,1.363395e+08,4.524929e+08,USA,2.106047e+13,3.138376e+12,-1.524487e+11,6.590602e+10,1.327510e+08
2020,868,Vietnam,23208.369000,7.847307e+07,1.138152e+08,VNM,3.466158e+11,3.285506e+10,-3.205025e+11,1.295970e+11,4.158416e+12
2020,869,South Africa,16.459105,2.082454e+07,1.523883e+07,ZAF,3.376197e+11,7.019955e+10,1.225049e+10,8.267567e+08,1.041074e+09

In [69]:
data = data.dropna()

In [96]:
deltaYGDP_lag1 = data['deltaGDP'].shift(1) / data['GDP(current $USD)'].shift(1)
deltaYGDP_lag2 = data['deltaGDP'].shift(2) / data['GDP(current $USD)'].shift(2)
deltaYGDP_lag3 = data['deltaGDP'].shift(3) / data['GDP(current $USD)'].shift(3)
GovtExp_lag1 = data['deltaGovtExp'].shift(1)
GovtExp_lag2 = data['deltaGovtExp'].shift(2)
GovtExp_lag3 = data['deltaGovtExp'].shift(3)

In [97]:
X = pd.DataFrame({
    'deltaYGDP_lag1': deltaYGDP_lag1,
    'deltaYGDP_lag2': deltaYGDP_lag2,
    'deltaYGDP_lag3': deltaYGDP_lag3,
    'GovtExp_lag1': GovtExp_lag1,
    'GovtExp_lag2': GovtExp_lag2,
    'GovtExp_lag3': GovtExp_lag3,
    'GShock' : data['GShock']
})
X

,deltaYGDP_lag1,deltaYGDP_lag2,deltaYGDP_lag3,GovtExp_lag1,GovtExp_lag2,GovtExp_lag3,GShock
year,,,,,,,
1993,NaN,NaN,NaN,NaN,NaN,NaN,3.572096e+05
1993,0.033594,NaN,NaN,2.517701e+10,NaN,NaN,9.942353e+06
1993,-0.042909,0.033594,NaN,-2.985383e+09,2.517701e+10,NaN,2.298880e+06
1993,0.108901,-0.042909,0.033594,9.057088e+09,-2.985383e+09,2.517701e+10,2.883368e+06
1993,-0.026365,0.108901,-0.042909,-6.982463e+09,9.057088e+09,-2.985383e+09,2.033050e+07
...,...,...,...,...,...,...,...
2020,-0.128583,0.026365,-0.078797,1.147335e+09,7.912346e+09,1.837954e+10,4.537596e+09
2020,-0.079347,-0.128583,0.026365,-7.999578e+09,1.147335e+09,7.912346e+09,1.017277e+08
2020,-0.095124,-0.079347,-0.128583,-7.260035e+08,-7.999578e+09,1.147335e+09,1.327510e+08
2020,-0.007239,-0.095124,-0.079347,6.590602e+10,-7.260035e+08,-7.999578e+09,4.158416e+12
2020,-0.924662,-0.007239,-0.095124,1.295970e+11,6.590602e+10,-7.260035e+08,1.041074e+09

In [98]:
X = X.fillna(method='bfill')

In [72]:
m = 3
deltaGDP_lag = [data.groupby('countryname')['deltaGDP'].shift(s) for s in range(1, m+1)]
deltaGovtExp_lag = [data.groupby('countryname')['deltaGovtExp'].shift(s) for s in range(1, m+1)]

In [45]:
import statsmodels.api as sm

In [75]:
Y = data['deltaGDP'] / data['GDP(current $USD)']
Y

year
1993    0.033594
1993   -0.042909
1993    0.108901
1993   -0.026365
1993   -0.288903
          ...
2020   -0.079347
2020   -0.095124
2020   -0.007239
2020   -0.924662
2020    0.036285
Length: 713, dtype: float64

In [89]:
X.isna().sum()

deltaYGDP_lag1    0
deltaYGDP_lag2    0
deltaYGDP_lag3    0
GShock_lag1       0
GShock_lag2       0
GShock_lag3       0
GShock            0
dtype: int64

In [84]:
X = data[['countryname','deltaGDP', 'deltaGovtExp', 'GShock']]

In [104]:
model = sm.OLS(Y, X).fit()
alpha_h = model.params['GShock'] / data['GDP(current $USD)'].mean()
beta_h = model.params[:3] / data['GDP(current $USD)'].mean()
zeta_h = model.params[3:6] / data['GDP(current $USD)'].mean()

In [105]:
alpha_h

6.833277966928808e-25

In [106]:
beta_h

deltaYGDP_lag1   -3.470143e-14
deltaYGDP_lag2    3.437613e-15
deltaYGDP_lag3    6.608946e-15
dtype: float64

In [107]:
zeta_h

GovtExp_lag1    6.092393e-24
GovtExp_lag2   -6.499242e-25
GovtExp_lag3    9.571368e-25
dtype: float64

In [108]:
model.params

deltaYGDP_lag1   -5.452817e-02
deltaYGDP_lag2    5.401702e-03
deltaYGDP_lag3    1.038498e-02
GovtExp_lag1      9.573297e-12
GovtExp_lag2     -1.021260e-12
GovtExp_lag3      1.503999e-12
GShock            1.073749e-12
dtype: float64