In [1]:
import pandas as pd
import numpy as np

In [2]:
pre_gs = pd.read_csv("./data/purified/gshock.csv")
pre_gs.head(30)

,Unnamed: 0,countryname,year,exchange rate (to $USD),import (thousand $USD),export (thousand $USD),countrycode,GDP(current $USD),general government final consumption expenditure (Current $USD)
0,0,United Arab Emirates,1992,3.671000,6.551802e+04,5.429537e+05,ARE,5.423917e+10,NaN
1,1,Argentina,1992,0.990642,2.001180e+05,1.241412e+05,ARG,2.287886e+11,6.807692e+09
2,2,Australia,1992,1.361648,1.671113e+06,6.607964e+05,AUS,3.255318e+11,6.346459e+10
3,3,Brazil,1992,0.001953,5.193021e+05,6.475174e+04,BRA,3.281880e+11,5.599876e+10
4,4,Canada,1992,1.208723,1.926517e+06,6.531780e+05,CAN,5.923877e+11,1.452958e+11
5,5,Switzerland,1992,1.406218,5.236438e+05,1.598710e+05,CHE,2.799214e+11,3.311095e+10
6,6,China,1992,5.514592,NaN,NaN,CHN,4.269157e+11,6.164946e+10
7,7,Germany,1992,1.561650,4.014989e+06,2.447975e+06,DEU,2.131572e+12,4.097120e+11
8,8,"Egypt, Arab Rep",1992,3.321748,NaN,NaN,EGY,4.185599e+10,4.363133e+09
9,9,Spain,1992,102.379080,3.556760e+05,3.534822e+05,ESP,6.309160e+11,1.123392e+11
10,10,France,1992,5.293816,1.495460e+06,7.642033e+05,FRA,1.401466e+12,3.119554e+11
11,11,United Kingdom,1992,0.569774,1.013577e+06,9.228269e+05,GBR,1.179660e+12,2.349036e+11
12,12,Indonesia,1992,2029.920800,1.554216e+06,4.714315e+05,IDN,1.280270e+11,1.218339e+10
13,13,India,1992,25.918083,1.809657e+05,1.584321e+05,IND,2.882084e+11,3.145808e+10
14,14,"Iran, Islamic Rep",1992,65.567841,NaN,NaN,IRN,8.041850e+11,NaN
15,15,Italy,1992,1232.405900,1.748231e+06,1.095468e+06,ITA,1.320162e+12,2.578330e+11
16,16,Japan,1992,126.651340,1.368241e+07,1.167870e+07,JPN,3.908809e+12,5.470532e+11
17,17,"Korea, Rep",1992,780.670840,NaN,NaN,KOR,3.555253e+11,3.932313e+10
18,18,Mexico,1992,3.094898,1.139809e+05,1.577332e+05,MEX,3.631576e+11,3.610830e+10
19,19,Malaysia,1992,2.547383,8.301400e+05,6.454289e+05,MYS,5.916755e+10,7.697805e+09
20,20,Netherlands,1992,1.758466,5.081722e+05,1.200323e+06,NLD,3.629629e+11,8.130886e+10
21,21,Philippines,1992,25.512491,1.550915e+05,2.095486e+05,PHL,6.042231e+10,5.588430e+09
22,22,Russian Federation,1992,NaN,3.526059e+06,2.336280e+06,RUS,4.602906e+11,6.378450e+10
23,23,Saudi Arabia,1992,3.750000,1.274090e+05,4.442515e+05,SAU,1.370879e+11,4.077225e+10
24,24,Singapore,1992,1.628967,1.235938e+06,2.030856e+06,SGP,5.213026e+10,4.601105e+09
25,25,Thailand,1992,25.400127,4.244984e+05,8.947945e+05,THA,1.114529e+11,1.103157e+10
26,26,Turkey,1992,0.006872,1.085494e+05,6.891213e+04,TUR,1.584591e+11,2.048087e+10
27,27,United States,1992,1.000000,8.900943e+06,8.599372e+06,USA,6.520327e+12,1.048383e+12
28,28,Vietnam,1992,11202.191000,7.270583e+04,1.063266e+05,VNM,9.866990e+09,NaN
29,29,South Africa,1992,2.852014,7.995050e+03,7.716677e+03,ZAF,1.469569e+11,2.630610e+10

In [3]:
ref_cn = pre_gs[pre_gs['countryname'] == 'China']
ref_cn

,Unnamed: 0,countryname,year,exchange rate (to $USD),import (thousand $USD),export (thousand $USD),countrycode,GDP(current $USD),general government final consumption expenditure (Current $USD)
6,6,China,1992,5.514592,NaN,NaN,CHN,4.269157e+11,6.164946e+10
36,36,China,1993,5.761958,NaN,NaN,CHN,4.447313e+11,6.383113e+10
66,66,China,1994,8.618743,NaN,NaN,CHN,5.643247e+11,7.952032e+10
96,96,China,1995,8.351417,NaN,NaN,CHN,7.345479e+11,9.775446e+10
126,126,China,1996,8.314175,NaN,NaN,CHN,8.637467e+11,1.139993e+11
156,156,China,1997,8.289817,NaN,NaN,CHN,9.616040e+11,1.322459e+11
186,186,China,1998,8.278958,NaN,NaN,CHN,1.029043e+12,1.538009e+11
216,216,China,1999,8.278250,NaN,NaN,CHN,1.093997e+12,1.790402e+11
246,246,China,2000,8.278504,NaN,NaN,CHN,1.211347e+12,2.039718e+11
276,276,China,2001,8.277068,NaN,NaN,CHN,1.339396e+12,2.198409e+11
306,306,China,2002,8.276957,NaN,NaN,CHN,1.470550e+12,2.363236e+11
336,336,China,2003,8.277037,NaN,NaN,CHN,1.660288e+12,2.542600e+11
366,366,China,2004,8.276801,NaN,NaN,CHN,1.955347e+12,2.859762e+11
396,396,China,2005,8.194317,NaN,NaN,CHN,2.285966e+12,3.382695e+11
426,426,China,2006,7.973438,NaN,NaN,CHN,2.752132e+12,4.078801e+11
456,456,China,2007,7.607532,NaN,NaN,CHN,3.550343e+12,5.193002e+11
486,486,China,2008,6.948655,NaN,NaN,CHN,4.594307e+12,6.655136e+11
516,516,China,2009,6.831416,NaN,NaN,CHN,5.101703e+12,7.526530e+11
546,546,China,2010,6.770269,NaN,NaN,CHN,6.087164e+12,8.879358e+11
576,576,China,2011,6.461462,NaN,NaN,CHN,7.551500e+12,1.150763e+12
606,606,China,2012,6.312333,NaN,NaN,CHN,8.532230e+12,1.344345e+12
636,636,China,2013,6.195758,NaN,NaN,CHN,9.570406e+12,1.520165e+12
666,666,China,2014,6.143434,NaN,NaN,CHN,1.047568e+13,1.656943e+12
696,696,China,2015,6.227488,NaN,NaN,CHN,1.106155e+13,1.793950e+12
726,726,China,2016,6.644478,NaN,NaN,CHN,1.123328e+13,1.838186e+12
756,756,China,2017,6.758755,NaN,NaN,CHN,1.231041e+13,2.009657e+12
786,786,China,2018,6.615957,NaN,NaN,CHN,1.389482e+13,2.297620e+12
816,816,China,2019,6.908385,NaN,NaN,CHN,1.427994e+13,2.394818e+12
846,846,China,2020,6.900767,NaN,NaN,CHN,1.468767e+13,2.516018e+12

In [4]:
ref_cn.reindex(ref_cn['year'])
ref_cn

,Unnamed: 0,countryname,year,exchange rate (to $USD),import (thousand $USD),export (thousand $USD),countrycode,GDP(current $USD),general government final consumption expenditure (Current $USD)
6,6,China,1992,5.514592,NaN,NaN,CHN,4.269157e+11,6.164946e+10
36,36,China,1993,5.761958,NaN,NaN,CHN,4.447313e+11,6.383113e+10
66,66,China,1994,8.618743,NaN,NaN,CHN,5.643247e+11,7.952032e+10
96,96,China,1995,8.351417,NaN,NaN,CHN,7.345479e+11,9.775446e+10
126,126,China,1996,8.314175,NaN,NaN,CHN,8.637467e+11,1.139993e+11
156,156,China,1997,8.289817,NaN,NaN,CHN,9.616040e+11,1.322459e+11
186,186,China,1998,8.278958,NaN,NaN,CHN,1.029043e+12,1.538009e+11
216,216,China,1999,8.278250,NaN,NaN,CHN,1.093997e+12,1.790402e+11
246,246,China,2000,8.278504,NaN,NaN,CHN,1.211347e+12,2.039718e+11
276,276,China,2001,8.277068,NaN,NaN,CHN,1.339396e+12,2.198409e+11
306,306,China,2002,8.276957,NaN,NaN,CHN,1.470550e+12,2.363236e+11
336,336,China,2003,8.277037,NaN,NaN,CHN,1.660288e+12,2.542600e+11
366,366,China,2004,8.276801,NaN,NaN,CHN,1.955347e+12,2.859762e+11
396,396,China,2005,8.194317,NaN,NaN,CHN,2.285966e+12,3.382695e+11
426,426,China,2006,7.973438,NaN,NaN,CHN,2.752132e+12,4.078801e+11
456,456,China,2007,7.607532,NaN,NaN,CHN,3.550343e+12,5.193002e+11
486,486,China,2008,6.948655,NaN,NaN,CHN,4.594307e+12,6.655136e+11
516,516,China,2009,6.831416,NaN,NaN,CHN,5.101703e+12,7.526530e+11
546,546,China,2010,6.770269,NaN,NaN,CHN,6.087164e+12,8.879358e+11
576,576,China,2011,6.461462,NaN,NaN,CHN,7.551500e+12,1.150763e+12
606,606,China,2012,6.312333,NaN,NaN,CHN,8.532230e+12,1.344345e+12
636,636,China,2013,6.195758,NaN,NaN,CHN,9.570406e+12,1.520165e+12
666,666,China,2014,6.143434,NaN,NaN,CHN,1.047568e+13,1.656943e+12
696,696,China,2015,6.227488,NaN,NaN,CHN,1.106155e+13,1.793950e+12
726,726,China,2016,6.644478,NaN,NaN,CHN,1.123328e+13,1.838186e+12
756,756,China,2017,6.758755,NaN,NaN,CHN,1.231041e+13,2.009657e+12
786,786,China,2018,6.615957,NaN,NaN,CHN,1.389482e+13,2.297620e+12
816,816,China,2019,6.908385,NaN,NaN,CHN,1.427994e+13,2.394818e+12
846,846,China,2020,6.900767,NaN,NaN,CHN,1.468767e+13,2.516018e+12

In [5]:
ref_cn['exchange rate (to $USD)'] = np.log(ref_cn['exchange rate (to $USD)'])
ref_cn['GDP(current $USD)'] = np.log(ref_cn['GDP(current $USD)'])
ref_cn['general government final consumption expenditure (Current $USD)'] = np.log10(ref_cn['general government final consumption expenditure (Current $USD)'])
ref_cn

/var/folders/c9/r_fs1r415jj4y9y9s18dj0ch0000gn/T/ipykernel_5687/1494452251.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ref_cn['exchange rate (to $USD)'] = np.log(ref_cn['exchange rate (to $USD)'])
/var/folders/c9/r_fs1r415jj4y9y9s18dj0ch0000gn/T/ipykernel_5687/1494452251.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ref_cn['GDP(current $USD)'] = np.log(ref_cn['GDP(current $USD)'])
/var/folders/c9/r_fs1r415jj4y9y9s18dj0ch0000gn/T/ipykernel_5687/1494452251.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ref_cn['general government final consumption expenditure (Current $USD)'] = np.log10(ref_cn['general government final consumption expenditure (Current $USD)'])

,Unnamed: 0,countryname,year,exchange rate (to $USD),import (thousand $USD),export (thousand $USD),countrycode,GDP(current $USD),general government final consumption expenditure (Current $USD)
6,6,China,1992,1.707398,NaN,NaN,CHN,26.779852,10.789929
36,36,China,1993,1.751277,NaN,NaN,CHN,26.820736,10.805033
66,66,China,1994,2.153939,NaN,NaN,CHN,27.058896,10.900478
96,96,China,1995,2.122431,NaN,NaN,CHN,27.322521,10.990137
126,126,China,1996,2.117962,NaN,NaN,CHN,27.484545,11.056902
156,156,China,1997,2.115028,NaN,NaN,CHN,27.591869,11.121382
186,186,China,1998,2.113717,NaN,NaN,CHN,27.659650,11.186959
216,216,China,1999,2.113632,NaN,NaN,CHN,27.720859,11.252951
246,246,China,2000,2.113662,NaN,NaN,CHN,27.822754,11.309570
276,276,China,2001,2.113489,NaN,NaN,CHN,27.923240,11.342109
306,306,China,2002,2.113475,NaN,NaN,CHN,28.016658,11.373507
336,336,China,2003,2.113485,NaN,NaN,CHN,28.138012,11.405278
366,366,China,2004,2.113457,NaN,NaN,CHN,28.301589,11.456330
396,396,China,2005,2.103441,NaN,NaN,CHN,28.457810,11.529263
426,426,China,2006,2.076116,NaN,NaN,CHN,28.643397,11.610533
456,456,China,2007,2.029139,NaN,NaN,CHN,28.898065,11.715418
486,486,China,2008,1.938548,NaN,NaN,CHN,29.155839,11.823157
516,516,China,2009,1.921532,NaN,NaN,CHN,29.260596,11.876595
546,546,China,2010,1.912541,NaN,NaN,CHN,29.437203,11.948382
576,576,China,2011,1.865856,NaN,NaN,CHN,29.652767,12.060986
606,606,China,2012,1.842505,NaN,NaN,CHN,29.774872,12.128511
636,636,China,2013,1.823865,NaN,NaN,CHN,29.889697,12.181891
666,666,China,2014,1.815384,NaN,NaN,CHN,29.980078,12.219308
696,696,China,2015,1.828973,NaN,NaN,CHN,30.034497,12.253810
726,726,China,2016,1.893786,NaN,NaN,CHN,30.049902,12.264389
756,756,China,2017,1.910839,NaN,NaN,CHN,30.141466,12.303122
786,786,China,2018,1.889485,NaN,NaN,CHN,30.262537,12.361278
816,816,China,2019,1.932736,NaN,NaN,CHN,30.289877,12.379273
846,846,China,2020,1.931633,NaN,NaN,CHN,30.318030,12.400714

In [6]:
pre_gs = pre_gs.dropna()

In [7]:
pre_gs['GShock'] = ''
pre_gs.head(3)

,Unnamed: 0,countryname,year,exchange rate (to $USD),import (thousand $USD),export (thousand $USD),countrycode,GDP(current $USD),general government final consumption expenditure (Current $USD),GShock
1,1,Argentina,1992,0.990642,200117.984,124141.240,ARG,2.287886e+11,6.807692e+09,
2,2,Australia,1992,1.361648,1671112.960,660796.352,AUS,3.255318e+11,6.346459e+10,
3,3,Brazil,1992,0.001953,519302.080,64751.736,BRA,3.281880e+11,5.599876e+10,

In [8]:
pre_gs['exchange rate (to $USD)'] = np.log(pre_gs['exchange rate (to $USD)'])
pre_gs['import (thousand $USD)'] = np.log(pre_gs['import (thousand $USD)'] * 1000)
pre_gs['export (thousand $USD)'] = np.log(pre_gs['export (thousand $USD)'] * 1000)
pre_gs['GDP(current $USD)'] = np.log(pre_gs['GDP(current $USD)'])
pre_gs['general government final consumption expenditure (Current $USD)'] = np.log(pre_gs['general government final consumption expenditure (Current $USD)'])

In [9]:
pre_gs.head(30)

,Unnamed: 0,countryname,year,exchange rate (to $USD),import (thousand $USD),export (thousand $USD),countrycode,GDP(current $USD),general government final consumption expenditure (Current $USD),GShock
1,1,Argentina,1992,-0.009402,19.114418,18.636931,ARG,26.156064,22.641319,
2,2,Australia,1992,0.308696,21.236756,20.308956,AUS,26.508726,24.873748,
3,3,Brazil,1992,-6.238377,20.067996,17.986071,BRA,26.516852,24.748595,
4,4,Canada,1992,0.189564,21.378980,20.297360,CAN,27.107427,25.702037,
5,5,Switzerland,1992,0.340904,20.076322,18.889878,CHE,26.357775,24.223130,
7,7,Germany,1992,0.445743,22.113300,21.618527,DEU,28.387881,26.738720,
9,9,Spain,1992,4.628682,19.689531,19.683344,ESP,27.170439,25.444788,
10,10,France,1992,1.666539,21.125700,20.454344,FRA,27.968540,26.466126,
11,11,United Kingdom,1992,-0.562515,20.736752,20.642952,GBR,27.796247,26.182441,
12,12,Indonesia,1992,7.615752,21.164237,19.971284,IDN,25.575507,23.223339,
13,13,India,1992,3.254941,19.013818,18.880837,IND,26.386950,24.171922,
15,15,Italy,1992,7.116724,21.281870,20.814447,ITA,27.908775,26.275578,
16,16,Japan,1992,4.841438,23.339377,23.181032,JPN,28.994254,27.027812,
18,18,Mexico,1992,1.129755,18.551541,18.876415,MEX,26.618103,24.309789,
19,19,Malaysia,1992,0.935067,20.537105,20.285426,MYS,24.803639,22.764201,
20,20,Netherlands,1992,0.564442,20.046331,20.905856,NLD,26.617566,25.121521,
21,21,Philippines,1992,3.239168,18.859526,19.160466,PHL,24.824624,22.443964,
23,23,Saudi Arabia,1992,1.321756,18.662913,19.911901,SAU,25.643888,24.431267,
24,24,Singapore,1992,0.487946,20.935096,21.431723,SGP,24.677011,22.249562,
25,25,Thailand,1992,3.234754,19.866419,20.612105,THA,25.436868,23.124027,
26,26,Turkey,1992,-4.980238,18.502716,18.048343,TUR,25.788763,23.742757,
27,27,United States,1992,0.000000,22.909423,22.874955,USA,29.505946,27.678270,
29,29,South Africa,1992,1.048025,15.894333,15.858894,ZAF,25.713405,23.993067,
31,31,Argentina,1993,-0.001055,19.208688,19.327646,ARG,26.190236,24.188524,
32,32,Australia,1993,0.385643,21.390805,20.782229,AUS,26.466712,24.825565,
33,33,Brazil,1993,-3.262916,20.576003,19.073871,BRA,26.632152,24.898512,
34,34,Canada,1993,0.254710,21.041839,20.903722,CAN,27.081404,25.652787,
35,35,Switzerland,1993,0.390430,20.728021,19.446490,CHE,26.329941,24.196248,
37,37,Germany,1993,0.502786,22.521779,22.101399,DEU,28.359209,26.716825,
39,39,Spain,1993,4.846235,19.979123,20.127585,ESP,26.986808,25.291005,

In [10]:
new_gs = []
for i in range(1992, 2021):
    cur = pre_gs[pre_gs['year'] == i]
    lastyear = pre_gs[pre_gs['year'] == i - 1]
    for index, row in cur.iterrows():
        if i >= 1993:
            new_gs.append(row['import (thousand $USD)'] 
                         / ref_cn.loc[ref_cn['year'] == i, 'general government final consumption expenditure (Current $USD)'].iloc[0]
                         * (row['export (thousand $USD)'] + row['import (thousand $USD)'])
                         / row['GDP(current $USD)'] * ref_cn.loc[ref_cn['year'] == i - 1, 'general government final consumption expenditure (Current $USD)'].iloc[0])
        else:
            new_gs.append(0)

In [11]:
new_gs

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 28.224172731800163,
 34.03725372255923,
 30.590677831277773,
 32.545506635640756,
 31.58283208669767,
 35.38845535858649,
 29.65066513626514,
 32.035312279711626,
 32.62809636195378,
 33.89219076042077,
 29.49449173415289,
 33.47365803427773,
 38.75710075112803,
 25.918157474157727,
 34.3177138153579,
 31.836549049832783,
 29.76520372935465,
 36.64494587976923,
 28.100518053183027,
 37.72335422576454,
 32.07705231035641,
 30.053738453300188,
 36.39422151057259,
 30.191211142423345,
 28.48213107853671,
 34.56430512576436,
 30.903410364459305,
 33.10918455302266,
 31.380728027676028,
 35.586289024115175,
 31.108895643904795,
 32.190555961047906,
 32.61566442145665,
 34.024616264811606,
 29.115298875913687,
 33.60717027373296,
 38.87105303539402,
 25.2658749728795,
 35.30279583216597,
 31.757935597377386,
 30.325227126288066,
 29.598317126250397,
 37.11030581880114,
 32.8816743155823,
 30.1297131894043,
 36.85071146099806,
 30.80813955704452,
 29.16205573038536,
 34.612734476643894,
 31.38837758745717,
 34.02065198098358,
 31.212060602693164,
 35.827276637662095,
 31.176698182225397,
 32.953940582255925,
 32.80073094817636,
 34.74424077440739,
 29.710658173699315,
 33.78642846200201,
 39.217829258830385,
 27.157646132697437,
 35.80419656338907,
 32.17230081546725,
 30.788017827944852,
 31.505753422460906,
 37.94194210879635,
 34.55089071926236,
 27.86141131054456,
 37.27593836722704,
 32.78193040328615,
 31.6988702704548,
 30.070561642551777,
 35.28320818418948,
 31.76641364453581,
 33.98772534792905,
 31.389890964832684,
 35.75108780331102,
 29.915025036527837,
 32.66659576590336,
 32.80052009742561,
 34.91264885508806,
 30.93319104737392,
 33.7272440534285,
 39.5434245616917,
 28.081376180036777,
 35.95717086598167,
 32.58566634195705,
 31.41723150007291,
 36.31524858192147,
 32.42484190926669,
 38.0939817201908,
 34.63890927055224,
 26.8783702218655,
 37.35210749887912,
 32.565999116199265,
 31.828789739640868,
 30.997189655684398,
 35.21669650352416,
 31.977599778997217,
 33.49057346546067,
 31.63703715687896,
 35.5940189707698,
 30.35202368229781,
 33.80075002349959,
 32.94734514071305,
 35.59143441644703,
 31.61555443258187,
 33.30589607549429,
 39.68653068051429,
 27.303783247242126,
 36.53293119569619,
 33.223264716823074,
 31.334188955350584,
 35.8648323915882,
 32.47230869136642,
 38.72823230906935,
 35.217852936191484,
 26.2431928707214,
 37.46643989713566,
 33.01649114462258,
 32.306136918498225,
 31.1055410919265,
 34.97819369424996,
 31.41076118988451,
 33.87023328312829,
 31.412850453300504,
 35.9766579808138,
 30.11610531027165,
 33.87659417438016,
 32.99378214440159,
 36.14107598963406,
 31.684864230797924,
 33.21625382818904,
 39.68879762874714,
 27.131152439524932,
 37.02518598294823,
 32.68837408051508,
 32.81398757848832,
 36.039422405158284,
 32.59788310365893,
 38.7454913056726,
 35.90588085724725,
 25.116744796053403,
 37.59478876474193,
 31.730793870935972,
 32.21657536854775,
 30.622913241965268,
 35.842627102221435,
 31.31211731235915,
 33.991652440681605,
 32.03900369955786,
 36.45641258827306,
 30.478769546773993,
 34.29922611667167,
 33.99867632429728,
 36.49159518543052,
 31.47396926510148,
 33.70754321756916,
 40.03216268415351,
 27.25908703580826,
 37.69883328130323,
 33.15182224871138,
 33.943523967877674,
 36.685434398177215,
 32.81678766553499,
 38.74093522860406,
 36.21854271634093,
 25.375361581740894,
 37.93893863924081,
 32.81143432182667,
 32.71935195173064,
 31.84992544214208,
 36.796596593805816,
 32.67329691304123,
 35.2405935551907,
 33.09273791886647,
 37.321099689265075,
 31.012072613932194,
 34.72619489809728,
 34.670132453439265,
 37.677850208467476,
 32.84890753819087,
 34.37253231118772,
 40.693060147119624,
 29.925327587878925,
 38.93754448173662,
 33.9102087378368,
 35.58342732082209,
 37.44077451012587,
 34.63350503591673,
 39.40329618356723,
 37.789680081437446,
 27.810994274403637,
 38.39434334813346,
 35.54645509610201,
 33.29330506730949,
 32.508837781939626,
 32.68773981708887,
 37.22836155116163,
 33.881475677393745,
 35.54448242144671,
 33.421296498130005,
 38.1280980807935,
 31.385623740536207,
 34.877694116349886,
 34.770229637244256,
 37.41709193155713,
 33.56362463928405,
 34.95065213743737,
 41.09865149413388,
 31.13031115128341,
 39.56717304170681,
 34.402355092416265,
 36.20355056555447,
 38.26212515067461,
 35.69697630484666,
 39.634112761599866,
 38.16894646721529,
 29.20267840726211,
 38.85104246466413,
 35.90369595942797,
 33.839278450782786,
 32.71326004508407,
 32.985055366266536,
 37.57256274621182,
 34.656604215066125,
 35.460333431808316,
 33.70246025788923,
 38.602153298268135,
 31.874745890174893,
 34.93720459014514,
 34.67844980938068,
 37.672165759441576,
 34.45836075575498,
 35.3076984876344,
 41.79353435444818,
 32.33738375519471,
 40.90668426787228,
 34.64555935154701,
 37.60002276667334,
 38.4571615042099,
 36.42213199774103,
 40.606276793336555,
 38.658901395316384,
 29.869379434704875,
 39.11026330260982,
 36.211607522709436,
 34.279782832923836,
 34.19877102734899,
 35.285591049232536,
 38.15503167708756,
 36.45918278992684,
 35.91642511851578,
 34.38504823599494,
 39.67416902958793,
 32.84836922492193,
 35.99703418040358,
 34.892443827912466,
 38.25511952225405,
 35.93460092774737,
 35.68037247246273,
 42.688297631497456,
 33.457319484322845,
 42.05564885408465,
 35.1951702850569,
 39.67815670065607,
 38.9701213652796,
 37.47954952614541,
 41.80717971213687,
 39.88177298302132,
 31.44126179782912,
 39.80526456284148,
 37.061653592006984,
 34.981336139718614,
 35.451315856461584,
 35.854717512385264,
 39.1526340114899,
 37.57221093330374,
 37.24171463710013,
 35.387680726511604,
 40.25831692588697,
 33.43671027125032,
 36.546530244355985,
 35.56168308756859,
 38.92859490063053,
 37.59015432504884,
 36.27920513963752,
 43.30028205029892,
 34.2169604177622,
 42.74434343037951,
 36.26939917718099,
 40.7261257985116,
 39.356825947360846,
 38.32473458868196,
 42.57866568562012,
 40.69297649444477,
 31.555853059068227,
 40.573391478373495,
 38.44343352292658,
 36.0489899724417,
 36.43394191933517,
 36.28110995043837,
 39.95013296797462,
 37.68516474333869,
 37.33505457304837,
 35.64924427223469,
 40.45961036761339,
 34.02052556213888,
 36.95317379245245,
 35.97265777703591,
 39.34749876887035,
 38.25580463709854,
 36.53381819104397,
 43.513305873245116,
 34.186144971295036,
 42.95241027101882,
 36.37830582092699,
 41.477422661905116,
 39.91587330827703,
 39.4240010668497,
 43.02256580614213,
 41.25011840648251,
 31.668171783292717,
 40.83482268380211,
 38.3209495145142,
 36.40310625518771,
 37.127518986758986,
 36.31973510394395,
 40.44716847472029,
 38.34805241367518,
 37.43324455818031,
 35.98642986558352,
 41.067919506095755,
 34.993142296786736,
 37.54408492357783,
 36.448830415483776,
 39.400063064535345,
 38.574223607756124,
 37.22024082222031,
 43.99809580332388,
 34.76924253409329,
 43.37336994967412,
 36.94764101414139,
 42.20662187676189,
 39.92025034176646,
 39.9714941170431,
 43.22852511310537,
 41.83424410742145,
 32.42243428524573,
 41.39483828542701,
 38.24948275226226,
 37.07496035176486,
 37.36409221906071,
 37.78205821336961,
 41.153040084271716,
 39.18572205650247,
 38.27981893840767,
 36.850713450913716,
 41.41128493902233,
 35.93956351390973,
 38.00498695352225,
 36.84788928678895,
 39.993472413709384,
 39.43530355314018,
 37.62358514920875,
 44.39343840237497,
 35.36356663508856,
 43.784589003121965,
 37.65741845449661,
 42.76716068429075,
 40.237330177126424,
 40.51969217824131,
 43.02801050413879,
 42.286838971464356,
 33.6185398281801,
 41.7544682550596,
 39.025927871104614,
 38.3008559847451,
 38.42261319340036,
 38.72751845362695,
 41.97507195844991,
 40.551078175358136,
 38.649882393636815,
 37.280351413729,
 41.96378936243212,
 36.46773085495132,
 38.36875669208627,
 37.507862256027124,
 40.35867218163236,
 40.5064062800715,
 38.00837717042011,
 44.63797136504346,
 35.716193760102634,
 43.959553607390184,
 37.759529557869016,
 42.22748223598756,
 40.486817891590704,
 41.938912372462795,
 43.356748730505046,
 42.68165541038759,
 34.45887645260405,
 42.18424490039507,
 39.625664069771275,
 39.347259266840915,
 37.24801682135224,
 36.75210192546262,
 42.437501992856,
 40.3821749094101,
 38.69485684795915,
 37.01364607568139,
 42.14875380749163,
 35.878814138713246,
 38.14036899659901,
 37.35472316462916,
 40.20704401157322,
 39.48764766980504,
 37.95052879876835,
 44.27831190293133,
 36.18351825220409,
 44.3257245493964,
 37.7898855713146,
 41.10458836854305,
 40.29114032804717,
 41.54894502882464,
 43.14585490498821,
 42.70844632482161,
 34.3666993055631,
 42.177965699207064,
 40.0112548900775,
 39.176802520607275,
 38.48528387803699,
 37.97425535783099,
 43.43839923714942,
 41.13824300620808,
 39.137908026208756,
 39.20856080223716,
 43.09088410467527,
 36.993943344381655,
 38.98775032333375,
 38.31382116342884,
 41.07412079667053,
 40.43949960460498,
 38.874018428692885,
 45.04836876774742,
 37.61653373846126,
 45.268152939281784,
 38.608732648747825,
 41.85309424063048,
 40.85716409543721,
 42.15578282282179,
 43.69385776909596,
 43.46360710176347,
 35.80053822755683,
 42.96559536905413,
 40.76821797139785,
 40.48710940453749,
 39.88000535342924,
 37.59682671177284,
 43.976270665187606,
 41.78827221698678,
 39.95931456965619,
 40.1729087374606,
 43.47337489087655,
 37.34876862443014,
 39.44467142207331,
 38.820597565606555,
 41.99499206903178,
 40.64991243341998,
 39.273199083255676,
 45.204523801128495,
 38.34872915770181,
 45.572871590238364,
 39.26732968786268,
 41.99122716375567,
 41.653972763573705,
 43.03928589098485,
 43.73187930891234,
 43.85761775009081,
 35.761358154996955,
 43.34021042091979,
 41.82562269478631,
 42.404088951244866,
 40.67443555534419,
 37.753276985017855,
 44.14016803817911,
 42.071063874583416,
 40.289853949356576,
 39.88930222390317,
 43.6228404858249,
 37.14539196229404,
 39.818216666889555,
 39.34336053124235,
 42.30174297056099,
 40.19860585076742,
 39.10500434100671,
 45.15082070840317,
 38.52537096965792,
 45.72827503074632,
 39.53025206483807,
 42.35009280217016,
 42.03615056657963,
 43.52704030580746,
 43.96792825179002,
 44.051688851453626,
 36.11788798923522,
 43.72465364538345,
 42.952267459785766,
 43.657459616833485,
 41.20683637954959,
 37.68295715700528,
 44.575504309388755,
 42.275744198640005,
 40.56809937844043,
 42.214623101337516,
 43.62717300889604,
 37.044484625251954,
 39.687077857339744,
 39.7458918442716,
 42.383697613384925,
 39.978354021059815,
 39.342595307799165,
 45.24015526368259,
 38.80962836756884,
 46.03524003215318,
 39.84307252470767,
 42.217383567585934,
 41.85768720896959,
 43.50055696140133,
 44.20134167586672,
 44.053568225883765,
 36.752997233134955,
 44.11339432458189,
 43.28162065164204,
 44.14413449842679,
 41.89105841093119,
 37.32024777017446,
 44.75004167618391,
 42.18878581409618,
 40.671014638173226,
 41.26597075190447,
 43.9740651078585,
 37.273499010102675,
 40.17340173134575,
 40.307595271840476,
 41.8708651257403,
 39.899800871015856,
 39.70547111744591,
 45.4034721551981,
 39.125368171901954,
 45.81066629745609,
 39.802832949357295,
 42.73275516538811,
 42.26232265017503,
 43.363419060834396,
 44.34882919536183,
 44.19290563577123,
 36.426047696769885,
 44.28281255741951,
 43.88722148587134,
 43.998886615215795,
 41.19611907938633,
 37.48773112236808,
 44.16331826831415,
 42.04218334667538,
 40.98242357159464,
 41.41122462127772,
 43.69237739226803,
 37.22143381564019,
 40.10993976380517,
 39.845881747824926,
 41.278883163918,
 39.41679835651958,
 39.57357821986055,
 45.13396904568658,
 39.062953929339855,
 45.85053097552392,
 39.80171602580606,
 42.537359002048746,
 41.9350710817346,
 42.37414175606706,
 44.14561634633955,
 44.244906780586255,
 35.95195963846889,
 44.07911118592756,
 45.00874376782162,
 43.118173589366535,
 40.726914954049214,
 37.207737627587505,
 44.26245102208575,
 42.03942827405626,
 40.114223936380874,
 41.42667257201172,
 43.63152543891695,
 37.463894655969455,
 39.875643685559425,
 39.950715381741226,
 41.375578796109714,
 39.05567611610362,
 39.559259229112804,
 45.04763291827763,
 39.29475931115215,
 45.57827563015597,
 40.102865926194305,
 42.42551016422573,
 42.098965734531184,
 41.718173040838174,
 43.8740608682227,
 44.354071747024165,
 35.79318765055362,
 43.831528771349745,
 45.51551928463261,
 42.30518147323243,
 41.056931421060995,
 36.9327746681029,
 44.886627688807536,
 42.61997089805362,
 40.303104412681066,
 40.827300530543766,
 43.8222092127376,
 38.017403859658735,
 40.249599057141175,
 40.33193007259713,
 41.97046717819714,
 39.714219982610466,
 40.0051692764603,
 45.36036531532392,
 39.528319841141524,
 45.74626456111808,
 40.410186864545445,
 42.6142297448258,
 42.45415504702628,
 42.28567444217251,
 44.41399464378746,
 44.32996052557342,
 36.54147532570318,
 44.10453858988089,
 46.25254545126773,
 42.32105197718801,
 41.6123921458657,
 36.3463782006306,
 45.10580283046495,
 43.515958688423815,
 41.107132913577544,
 41.315338345499185,
 43.956545233761204,
 38.13282633023013,
 40.63487274493212,
 40.33600220299832,
 42.52083307864434,
 40.07913316730843,
 40.02676961540464,
 45.54324287658595,
 39.995124804659014,
 45.966167609167975,
 40.51283242873248,
 42.72425999851803,
 43.34047189334406,
 42.87433514059614,
 44.22396664588965,
 44.375949537862674,
 36.583368594934434,
 44.075785922067254,
 46.827505756792235,
 42.546683548685685,
 41.734887081251095,
 38.37867177141968,
 45.67972395401002,
 43.821661661270284,
 41.250582309501056,
 40.67975493276197,
 44.128501944680615,
 38.30327775039549,
 40.8881421690139,
 40.566895471663514,
 42.59574600418764,
 40.00877757083861,
 40.26520531691038,
 45.509132421247166,
 40.174554419118245,
 46.5761654984112,
 40.41558957062562,
 42.810778305242486,
 43.57089333900042,
 43.76642816408303,
 44.59617409143715,
 44.55108304445771,
 36.536902475726684,
 43.4617537673073,
 46.998645052823115,
 42.628613665148826,
 42.258789756477455,
 38.400755496771204,
 45.758369579482384,
 44.37547026024598,
 40.80888690844947,
 39.573502048667386,
 44.19001928780866,
 38.90426667141519,
 40.78596266718956,
 40.28802647938979,
 42.822859982427175,
 40.37473040585655,
 40.418124138994166,
 45.562093561340085,
 40.6718707031299,
 46.899436324213276,
 40.80370032876379,
 42.7708238405716,
 43.62273561998731,
 43.23902589643268,
 44.47192033329769,
 44.88770424365851,
 36.88832475176439,
 43.77952916439365,
 47.635735803878404,
 42.17936095852758]

In [12]:
pre_gs['GShock'] = new_gs
pre_gs

,Unnamed: 0,countryname,year,exchange rate (to $USD),import (thousand $USD),export (thousand $USD),countrycode,GDP(current $USD),general government final consumption expenditure (Current $USD),GShock
1,1,Argentina,1992,-0.009402,19.114418,18.636931,ARG,26.156064,22.641319,0.000000
2,2,Australia,1992,0.308696,21.236756,20.308956,AUS,26.508726,24.873748,0.000000
3,3,Brazil,1992,-6.238377,20.067996,17.986071,BRA,26.516852,24.748595,0.000000
4,4,Canada,1992,0.189564,21.378980,20.297360,CAN,27.107427,25.702037,0.000000
5,5,Switzerland,1992,0.340904,20.076322,18.889878,CHE,26.357775,24.223130,0.000000
...,...,...,...,...,...,...,...,...,...,...
865,865,Thailand,2020,3.443416,24.597369,24.645500,THA,26.937237,25.213549,44.887704
866,866,Turkey,2020,1.947139,22.039949,23.736171,TUR,27.302919,25.417310,36.888325
867,867,United States,2020,0.000000,25.638414,26.838038,USA,30.678419,28.774727,43.779529
868,868,Vietnam,2020,10.052268,25.086021,25.457842,VNM,26.571483,24.215372,47.635736
869,869,South Africa,2020,2.800879,23.759398,23.447112,ZAF,26.545186,24.974608,42.179361

In [13]:
data = pre_gs.set_index('year')
data = data.dropna()

In [14]:
data

,Unnamed: 0,countryname,exchange rate (to $USD),import (thousand $USD),export (thousand $USD),countrycode,GDP(current $USD),general government final consumption expenditure (Current $USD),GShock
year,,,,,,,,,
1992,1,Argentina,-0.009402,19.114418,18.636931,ARG,26.156064,22.641319,0.000000
1992,2,Australia,0.308696,21.236756,20.308956,AUS,26.508726,24.873748,0.000000
1992,3,Brazil,-6.238377,20.067996,17.986071,BRA,26.516852,24.748595,0.000000
1992,4,Canada,0.189564,21.378980,20.297360,CAN,27.107427,25.702037,0.000000
1992,5,Switzerland,0.340904,20.076322,18.889878,CHE,26.357775,24.223130,0.000000
...,...,...,...,...,...,...,...,...,...
2020,865,Thailand,3.443416,24.597369,24.645500,THA,26.937237,25.213549,44.887704
2020,866,Turkey,1.947139,22.039949,23.736171,TUR,27.302919,25.417310,36.888325
2020,867,United States,0.000000,25.638414,26.838038,USA,30.678419,28.774727,43.779529
2020,868,Vietnam,10.052268,25.086021,25.457842,VNM,26.571483,24.215372,47.635736
2020,869,South Africa,2.800879,23.759398,23.447112,ZAF,26.545186,24.974608,42.179361

In [15]:
data['deltaGDP'] = data.groupby('countryname')['GDP(current $USD)'].diff()
data

,Unnamed: 0,countryname,exchange rate (to $USD),import (thousand $USD),export (thousand $USD),countrycode,GDP(current $USD),general government final consumption expenditure (Current $USD),GShock,deltaGDP
year,,,,,,,,,,
1992,1,Argentina,-0.009402,19.114418,18.636931,ARG,26.156064,22.641319,0.000000,NaN
1992,2,Australia,0.308696,21.236756,20.308956,AUS,26.508726,24.873748,0.000000,NaN
1992,3,Brazil,-6.238377,20.067996,17.986071,BRA,26.516852,24.748595,0.000000,NaN
1992,4,Canada,0.189564,21.378980,20.297360,CAN,27.107427,25.702037,0.000000,NaN
1992,5,Switzerland,0.340904,20.076322,18.889878,CHE,26.357775,24.223130,0.000000,NaN
...,...,...,...,...,...,...,...,...,...,...
2020,865,Thailand,3.443416,24.597369,24.645500,THA,26.937237,25.213549,44.887704,-0.053583
2020,866,Turkey,1.947139,22.039949,23.736171,TUR,27.302919,25.417310,36.888325,-0.179030
2020,867,United States,0.000000,25.638414,26.838038,USA,30.678419,28.774727,43.779529,-0.054835
2020,868,Vietnam,10.052268,25.086021,25.457842,VNM,26.571483,24.215372,47.635736,-0.015104
2020,869,South Africa,2.800879,23.759398,23.447112,ZAF,26.545186,24.974608,42.179361,0.035983

In [16]:
data['deltaGovtExp'] = data.groupby('countryname')['general government final consumption expenditure (Current $USD)'].diff()

data

,Unnamed: 0,countryname,exchange rate (to $USD),import (thousand $USD),export (thousand $USD),countrycode,GDP(current $USD),general government final consumption expenditure (Current $USD),GShock,deltaGDP,deltaGovtExp
year,,,,,,,,,,,
1992,1,Argentina,-0.009402,19.114418,18.636931,ARG,26.156064,22.641319,0.000000,NaN,NaN
1992,2,Australia,0.308696,21.236756,20.308956,AUS,26.508726,24.873748,0.000000,NaN,NaN
1992,3,Brazil,-6.238377,20.067996,17.986071,BRA,26.516852,24.748595,0.000000,NaN,NaN
1992,4,Canada,0.189564,21.378980,20.297360,CAN,27.107427,25.702037,0.000000,NaN,NaN
1992,5,Switzerland,0.340904,20.076322,18.889878,CHE,26.357775,24.223130,0.000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2020,865,Thailand,3.443416,24.597369,24.645500,THA,26.937237,25.213549,44.887704,-0.053583,-0.070638
2020,866,Turkey,1.947139,22.039949,23.736171,TUR,27.302919,25.417310,36.888325,-0.179030,-0.014274
2020,867,United States,0.000000,25.638414,26.838038,USA,30.678419,28.774727,43.779529,-0.054835,0.114512
2020,868,Vietnam,10.052268,25.086021,25.457842,VNM,26.571483,24.215372,47.635736,-0.015104,0.042171
2020,869,South Africa,2.800879,23.759398,23.447112,ZAF,26.545186,24.974608,42.179361,0.035983,0.025486

In [17]:
data = data.dropna()

In [18]:
deltaYGDP_lag1 = data['deltaGDP'].shift(1) / data['GDP(current $USD)'].shift(1)
deltaYGDP_lag2 = data['deltaGDP'].shift(2) / data['GDP(current $USD)'].shift(2)
deltaYGDP_lag3 = data['deltaGDP'].shift(3) / data['GDP(current $USD)'].shift(3)
GovtExp_lag1 = data['deltaGovtExp'].shift(1)
GovtExp_lag2 = data['deltaGovtExp'].shift(2)
GovtExp_lag3 = data['deltaGovtExp'].shift(3)

In [19]:
X = pd.DataFrame({
    'deltaYGDP_lag1': deltaYGDP_lag1,
    'deltaYGDP_lag2': deltaYGDP_lag2,
    'deltaYGDP_lag3': deltaYGDP_lag3,
    'GovtExp_lag1': GovtExp_lag1,
    'GovtExp_lag2': GovtExp_lag2,
    'GovtExp_lag3': GovtExp_lag3,
    'GShock' : data['GShock']
})
X

,deltaYGDP_lag1,deltaYGDP_lag2,deltaYGDP_lag3,GovtExp_lag1,GovtExp_lag2,GovtExp_lag3,GShock
year,,,,,,,
1993,NaN,NaN,NaN,NaN,NaN,NaN,28.224173
1993,0.001305,NaN,NaN,1.547205,NaN,NaN,34.037254
1993,-0.001587,0.001305,NaN,-0.048183,1.547205,NaN,30.590678
1993,0.004329,-0.001587,0.001305,0.149917,-0.048183,1.547205,32.545507
1993,-0.000961,0.004329,-0.001587,-0.049250,0.149917,-0.048183,31.582832
...,...,...,...,...,...,...,...
2020,-0.003204,0.000930,-0.003137,0.012954,0.092212,0.067551,44.887704
2020,-0.001989,-0.003204,0.000930,-0.070638,0.012954,0.092212,36.888325
2020,-0.006557,-0.001989,-0.003204,-0.014274,-0.070638,0.012954,43.779529
2020,-0.001787,-0.006557,-0.001989,0.114512,-0.014274,-0.070638,47.635736
2020,-0.000568,-0.001787,-0.006557,0.042171,0.114512,-0.014274,42.179361

In [20]:
X = X.fillna(method='bfill')

In [21]:
X

,deltaYGDP_lag1,deltaYGDP_lag2,deltaYGDP_lag3,GovtExp_lag1,GovtExp_lag2,GovtExp_lag3,GShock
year,,,,,,,
1993,0.001305,0.001305,0.001305,1.547205,1.547205,1.547205,28.224173
1993,0.001305,0.001305,0.001305,1.547205,1.547205,1.547205,34.037254
1993,-0.001587,0.001305,0.001305,-0.048183,1.547205,1.547205,30.590678
1993,0.004329,-0.001587,0.001305,0.149917,-0.048183,1.547205,32.545507
1993,-0.000961,0.004329,-0.001587,-0.049250,0.149917,-0.048183,31.582832
...,...,...,...,...,...,...,...
2020,-0.003204,0.000930,-0.003137,0.012954,0.092212,0.067551,44.887704
2020,-0.001989,-0.003204,0.000930,-0.070638,0.012954,0.092212,36.888325
2020,-0.006557,-0.001989,-0.003204,-0.014274,-0.070638,0.012954,43.779529
2020,-0.001787,-0.006557,-0.001989,0.114512,-0.014274,-0.070638,47.635736
2020,-0.000568,-0.001787,-0.006557,0.042171,0.114512,-0.014274,42.179361

In [22]:
m = 3
deltaGDP_lag = [data.groupby('countryname')['deltaGDP'].shift(s) for s in range(1, m+1)]
deltaGovtExp_lag = [data.groupby('countryname')['deltaGovtExp'].shift(s) for s in range(1, m+1)]

In [23]:
import statsmodels.api as sm

In [24]:
Y = data['deltaGDP'] / data['GDP(current $USD)']
Y

year
1993    0.001305
1993   -0.001587
1993    0.004329
1993   -0.000961
1993   -0.002194
          ...
2020   -0.001989
2020   -0.006557
2020   -0.001787
2020   -0.000568
2020    0.001356
Length: 713, dtype: float64

In [25]:
X.isna().sum()

deltaYGDP_lag1    0
deltaYGDP_lag2    0
deltaYGDP_lag3    0
GovtExp_lag1      0
GovtExp_lag2      0
GovtExp_lag3      0
GShock            0
dtype: int64

In [26]:
# X = data[['countryname','deltaGDP', 'deltaGovtExp', 'GShock']]

In [27]:
model = sm.OLS(Y, X).fit()
alpha_h = model.params['GShock'] / data['GDP(current $USD)']
beta_h = model.params[:3] / data['GDP(current $USD)'].mean()
zeta_h = model.params[3:6] / data['GDP(current $USD)'].mean()

In [28]:
alpha_h

year
1993    7.048691e-07
1993    6.975059e-07
1993    6.931730e-07
1993    6.816740e-07
1993    7.011291e-07
            ...
2020    6.853223e-07
2020    6.761434e-07
2020    6.017483e-07
2020    6.947557e-07
2020    6.954439e-07
Name: GDP(current $USD), Length: 713, dtype: float64

In [29]:
beta_h

deltaYGDP_lag1    0.015108
deltaYGDP_lag2    0.002135
deltaYGDP_lag3    0.006778
dtype: float64

In [30]:
zeta_h

GovtExp_lag1   -0.000237
GovtExp_lag2    0.000104
GovtExp_lag3    0.000025
dtype: float64

In [31]:
model.params

deltaYGDP_lag1    0.411841
deltaYGDP_lag2    0.058192
deltaYGDP_lag3    0.184756
GovtExp_lag1     -0.006465
GovtExp_lag2      0.002844
GovtExp_lag3      0.000680
GShock            0.000018
dtype: float64

In [32]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.288
Model:                            OLS   Adj. R-squared (uncentered):              0.281
Method:                 Least Squares   F-statistic:                              40.78
Date:                Wed, 07 Jun 2023   Prob (F-statistic):                    2.84e-48
Time:                        17:49:07   Log-Likelihood:                          2894.0
No. Observations:                 713   AIC:                                     -5774.
Df Residuals:                     706   BIC:                                     -5742.
Df Model:                           7
Covariance Type:            nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
deltaYGDP_lag1     0.4118      0.071      5.828      0.000       0.273       0.551
deltaYGDP_lag2     0.0582      0.075      0.775      0.438      -0.089       0.206
deltaYGDP_lag3     0.1848      0.064      2.868      0.004       0.058       0.311
GovtExp_lag1      -0.0065      0.002     -3.012      0.003      -0.011      -0.002
GovtExp_lag2       0.0028      0.002      1.283      0.200      -0.002       0.007
GovtExp_lag3       0.0007      0.002      0.369      0.713      -0.003       0.004
GShock          1.846e-05    4.6e-06      4.016      0.000    9.44e-06    2.75e-05
==============================================================================
Omnibus:                      404.775   Durbin-Watson:                   2.078
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9672.271
Skew:                          -2.053   Prob(JB):                         0.00
Kurtosis:                      20.570   Cond. No.                     2.21e+04
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 2.21e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""